# Generated by Django 3.0.3 on 2020-07-02 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 22, 10, 1, 500659, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
